/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cf_wayzer_imeFix_JNIImpl */

#ifndef _Included_cf_wayzer_imeFix_JNIImpl
#define _Included_cf_wayzer_imeFix_JNIImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cf_wayzer_imeFix_JNIImpl
 * Method:    setup
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cf_wayzer_imeFix_JNIImpl_setup
  (JNIEnv *, jclass);

/*
 * Class:     cf_wayzer_imeFix_JNIImpl
 * Method:    setPos
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_cf_wayzer_imeFix_JNIImpl_setPos
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cf_wayzer_imeFix_JNIImpl
 * Method:    setOpen
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_cf_wayzer_imeFix_JNIImpl_setOpen
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
